# __  ___                           ____                     __
# \ \/ | |_ _ __ ___ _ __ ___   ___/ ___| _ __   ___   ___  / _| ___ _ __
#  \  /| __| '__/ _ | '_ ` _ \ / _ \___ \| '_ \ / _ \ / _ \| |_ / _ | '__|
#  /  \| |_| | |  __| | | | | |  __/___) | |_) | (_) | (_) |  _|  __| |
# /_/\_\\__|_|  \___|_| |_| |_|\___|____/| .__/ \___/ \___/|_|  \___|_|
#                                        |_|
#
# Wiki: https://xtreme.gitbook.io/xtremespoofer/

# Port:
# Use a free port with which the plugin can connect to your Spigot servers. 
port: 5723

# Servers:
# Configure the servers of your network that contain fake players.
servers:
  lobby: # Set the same server name as you have set in the Bungee configuration.
    port: 5721 # Enter the port you have set in the plugin configuration in Spigot.
  survival:
    port: 5722