# __  ___                           ____                     __
# \ \/ | |_ _ __ ___ _ __ ___   ___/ ___| _ __   ___   ___  / _| ___ _ __
#  \  /| __| '__/ _ | '_ ` _ \ / _ \___ \| '_ \ / _ \ / _ \| |_ / _ | '__|
#  /  \| |_| | |  __| | | | | |  __/___) | |_) | (_) | (_) |  _|  __| |
# /_/\_\\__|_|  \___|_| |_| |_|\___|____/| .__/ \___/ \___/|_|  \___|_|
#                                        |_|
#
# Wiki: https://xtreme.gitbook.io/xtremespoofer/

# Metrics:
# This plugin uses the bStats metrics system. If you want your data not to be collected, you can disable this system here.
# The following information is collected and sent to bstats.org:
#      Whether the server is in offline or online mode
#      The plugin version
#      The server version
#      The java version
#      The OS version/name and architecture
#      The location of your server
#      The core count for the CPU
#      The number of players online
#      The Metrics version
metrics: true

# Enabled:
# Enables or disables counter spoofing without the need to remove the plugin.
enabled: true

# Port:
# Use a free port with which the plugin can connect to your Spigot servers. 
port: 5723

# Max:
# Spoof the counter of the maximum number of connected players. (If you don't want to fake it you can put the real number).
max: 150

# Limit:
# Limit of online players. When the counter reaches this number, it will stop counting.
limit: 100

